apiVersion: v1
kind: ReplicationController
metadata:
  name: logstash
  namespace: default
  labels:
    component: elk
    role: logstash
spec:
  replicas: 1
  selector:
    component: elk
    role: logstash
  template:
    metadata:
      labels:
        component: elk
        role: logstash
    spec:
      serviceAccount: elk
      containers:
      - command: ["/logstash/bin/logstash", "-f", "/logstash/config/logstash.conf", "--verbose"]
        name: logstash
        image: tangfeixiong/logstash:2.3.2 # pires/logstash
        imagePullPolicy: IfNotPresent
        env:
        - name: KUBERNETES_TRUST_CERT
          value: "true"
        ports:
        - containerPort: 5043
          name: lumberjack
          protocol: TCP
        volumeMounts:
        - mountPath: /logstash/certs
          name: certs
        - mountPath: /logstash/config
          name: config
      volumes:
      - emptyDir: {}
          # medium: ""
        name: "storage"
      - hostPath:
          path: "/data/src/github.com/pires/kubernetes-elk-cluster/certs" # "/tmp"
        name: "certs"
      - hostPath:
          path: "/data/src/github.com/pires/kubernetes-elk-cluster/config"
        name: "config"
